/* Generated by Yosys 0.20+22 (git sha1 c26b2bf54, clang 10.0.0-4ubuntu1 -fPIC -Os) */

module iiitb_pwm_gen(clk, increase_duty, decrease_duty, reset, PWM_OUT);
  wire [3:0] _000_;
  wire [27:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire [3:0] DUTY_CYCLE;
  output PWM_OUT;
  wire PWM_OUT;
  input clk;
  wire clk;
  wire [3:0] counter_PWM;
  wire [27:0] counter_debounce;
  input decrease_duty;
  wire decrease_duty;
  input increase_duty;
  wire increase_duty;
  input reset;
  wire reset;
  wire tmp1;
  wire tmp2;
  wire tmp3;
  wire tmp4;
  sky130_fd_sc_hd__clkinv_1 _137_ (
    .A(tmp4),
    .Y(_050_)
  );
  sky130_fd_sc_hd__clkinv_1 _138_ (
    .A(counter_debounce[0]),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nor4_1 _139_ (
    .A(counter_debounce[1]),
    .B(counter_debounce[3]),
    .C(counter_debounce[2]),
    .D(_051_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nor4_1 _140_ (
    .A(counter_debounce[4]),
    .B(counter_debounce[5]),
    .C(counter_debounce[7]),
    .D(counter_debounce[6]),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nor4_1 _141_ (
    .A(counter_debounce[13]),
    .B(counter_debounce[12]),
    .C(counter_debounce[15]),
    .D(counter_debounce[14]),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nor4_1 _142_ (
    .A(counter_debounce[9]),
    .B(counter_debounce[8]),
    .C(counter_debounce[11]),
    .D(counter_debounce[10]),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nand4_1 _143_ (
    .A(_052_),
    .B(_053_),
    .C(_054_),
    .D(_055_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nor4_1 _144_ (
    .A(counter_debounce[25]),
    .B(counter_debounce[24]),
    .C(counter_debounce[27]),
    .D(counter_debounce[26]),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nor4_1 _145_ (
    .A(counter_debounce[20]),
    .B(counter_debounce[21]),
    .C(counter_debounce[23]),
    .D(counter_debounce[22]),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nor4_1 _146_ (
    .A(counter_debounce[17]),
    .B(counter_debounce[16]),
    .C(counter_debounce[18]),
    .D(counter_debounce[19]),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nand3_1 _147_ (
    .A(_057_),
    .B(_058_),
    .C(_059_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nor2_1 _148_ (
    .A(_060_),
    .B(_056_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nand2_1 _149_ (
    .A(_061_),
    .B(tmp3),
    .Y(_062_)
  );
  sky130_fd_sc_hd__o21ai_0 _150_ (
    .A1(_050_),
    .A2(_061_),
    .B1(_062_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__clkinv_1 _151_ (
    .A(tmp3),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nand2_1 _152_ (
    .A(_061_),
    .B(decrease_duty),
    .Y(_064_)
  );
  sky130_fd_sc_hd__o21ai_0 _153_ (
    .A1(_063_),
    .A2(_061_),
    .B1(_064_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__clkinv_1 _154_ (
    .A(tmp2),
    .Y(_065_)
  );
  sky130_fd_sc_hd__clkinv_1 _155_ (
    .A(counter_debounce[11]),
    .Y(_066_)
  );
  sky130_fd_sc_hd__clkinv_1 _156_ (
    .A(counter_debounce[12]),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand3_1 _157_ (
    .A(_066_),
    .B(_067_),
    .C(counter_debounce[0]),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nor2_1 _158_ (
    .A(counter_debounce[3]),
    .B(counter_debounce[4]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nor2_1 _159_ (
    .A(counter_debounce[19]),
    .B(counter_debounce[20]),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nand2_1 _160_ (
    .A(_069_),
    .B(_070_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nor2_1 _161_ (
    .A(_068_),
    .B(_071_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nor2_1 _162_ (
    .A(counter_debounce[5]),
    .B(counter_debounce[6]),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nor2_1 _163_ (
    .A(counter_debounce[13]),
    .B(counter_debounce[14]),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nand2_1 _164_ (
    .A(_073_),
    .B(_074_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__clkinv_1 _165_ (
    .A(counter_debounce[27]),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nor2_1 _166_ (
    .A(counter_debounce[23]),
    .B(counter_debounce[24]),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nand2_1 _167_ (
    .A(_077_),
    .B(_076_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nor2_1 _168_ (
    .A(_078_),
    .B(_075_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nor2_1 _169_ (
    .A(counter_debounce[21]),
    .B(counter_debounce[22]),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nor2_1 _170_ (
    .A(counter_debounce[25]),
    .B(counter_debounce[26]),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nor2_1 _171_ (
    .A(counter_debounce[9]),
    .B(counter_debounce[10]),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nor2_1 _172_ (
    .A(counter_debounce[17]),
    .B(counter_debounce[18]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nand4_1 _173_ (
    .A(_080_),
    .B(_081_),
    .C(_082_),
    .D(_083_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nor2_1 _174_ (
    .A(counter_debounce[1]),
    .B(counter_debounce[2]),
    .Y(_085_)
  );
  sky130_fd_sc_hd__nor2_1 _175_ (
    .A(counter_debounce[7]),
    .B(counter_debounce[8]),
    .Y(_086_)
  );
  sky130_fd_sc_hd__nor2_1 _176_ (
    .A(counter_debounce[15]),
    .B(counter_debounce[16]),
    .Y(_087_)
  );
  sky130_fd_sc_hd__nand3_1 _177_ (
    .A(_085_),
    .B(_086_),
    .C(_087_),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nor2_1 _178_ (
    .A(_088_),
    .B(_084_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nand4_1 _179_ (
    .A(_089_),
    .B(tmp1),
    .C(_072_),
    .D(_079_),
    .Y(_090_)
  );
  sky130_fd_sc_hd__o21ai_0 _180_ (
    .A1(_065_),
    .A2(_061_),
    .B1(_090_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__mux2_2 _181_ (
    .A0(tmp1),
    .A1(increase_duty),
    .S(_061_),
    .X(_046_)
  );
  sky130_fd_sc_hd__nor2_1 _182_ (
    .A(counter_debounce[11]),
    .B(_051_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nand4_1 _183_ (
    .A(_091_),
    .B(_067_),
    .C(_069_),
    .D(_070_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nand4_1 _184_ (
    .A(_073_),
    .B(_074_),
    .C(_077_),
    .D(_076_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nor2_1 _185_ (
    .A(_093_),
    .B(_092_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nand2_1 _186_ (
    .A(_094_),
    .B(_089_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__o21ai_0 _187_ (
    .A1(DUTY_CYCLE[2]),
    .A2(DUTY_CYCLE[1]),
    .B1(DUTY_CYCLE[3]),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nand2_1 _188_ (
    .A(_096_),
    .B(_065_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__clkinv_1 _189_ (
    .A(_097_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nand4_1 _190_ (
    .A(_094_),
    .B(tmp1),
    .C(_089_),
    .D(_098_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__o41ai_1 _191_ (
    .A1(DUTY_CYCLE[3]),
    .A2(DUTY_CYCLE[2]),
    .A3(DUTY_CYCLE[1]),
    .A4(DUTY_CYCLE[0]),
    .B1(_050_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__o31ai_1 _192_ (
    .A1(_063_),
    .A2(_100_),
    .A3(_095_),
    .B1(_099_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__clkinv_1 _193_ (
    .A(DUTY_CYCLE[2]),
    .Y(_102_)
  );
  sky130_fd_sc_hd__clkinv_1 _194_ (
    .A(DUTY_CYCLE[1]),
    .Y(_103_)
  );
  sky130_fd_sc_hd__clkinv_1 _195_ (
    .A(DUTY_CYCLE[0]),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nand4_1 _196_ (
    .A(_099_),
    .B(_102_),
    .C(_103_),
    .D(_104_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__nor2_1 _197_ (
    .A(_097_),
    .B(_090_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__nand4_1 _198_ (
    .A(_106_),
    .B(DUTY_CYCLE[2]),
    .C(DUTY_CYCLE[1]),
    .D(DUTY_CYCLE[0]),
    .Y(_107_)
  );
  sky130_fd_sc_hd__nand2_1 _199_ (
    .A(_107_),
    .B(_105_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__a21oi_1 _200_ (
    .A1(_108_),
    .A2(_101_),
    .B1(DUTY_CYCLE[3]),
    .Y(_109_)
  );
  sky130_fd_sc_hd__clkinv_1 _201_ (
    .A(DUTY_CYCLE[3]),
    .Y(_110_)
  );
  sky130_fd_sc_hd__o31a_2 _202_ (
    .A1(_063_),
    .A2(_100_),
    .A3(_095_),
    .B1(_099_),
    .X(_111_)
  );
  sky130_fd_sc_hd__a211oi_1 _203_ (
    .A1(_107_),
    .A2(_105_),
    .B1(_110_),
    .C1(_111_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__nor2_1 _204_ (
    .A(_112_),
    .B(_109_),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nor3_1 _205_ (
    .A(_063_),
    .B(_100_),
    .C(_095_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__nand4_1 _206_ (
    .A(_113_),
    .B(_103_),
    .C(_104_),
    .D(_099_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__nand3_1 _207_ (
    .A(_106_),
    .B(DUTY_CYCLE[1]),
    .C(DUTY_CYCLE[0]),
    .Y(_115_)
  );
  sky130_fd_sc_hd__and3_2 _208_ (
    .A(_114_),
    .B(_102_),
    .C(_115_),
    .X(_116_)
  );
  sky130_fd_sc_hd__a21oi_1 _209_ (
    .A1(_114_),
    .A2(_115_),
    .B1(_102_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__nor2_1 _210_ (
    .A(_117_),
    .B(_116_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nand2_1 _211_ (
    .A(_099_),
    .B(DUTY_CYCLE[1]),
    .Y(_118_)
  );
  sky130_fd_sc_hd__clkinv_1 _212_ (
    .A(_118_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__nor2_1 _213_ (
    .A(DUTY_CYCLE[1]),
    .B(_099_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__o21ai_0 _214_ (
    .A1(_120_),
    .A2(_119_),
    .B1(DUTY_CYCLE[0]),
    .Y(_121_)
  );
  sky130_fd_sc_hd__nand3b_1 _215_ (
    .A_N(_120_),
    .B(_104_),
    .C(_118_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__nor2_1 _216_ (
    .A(DUTY_CYCLE[1]),
    .B(_101_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__a31oi_1 _217_ (
    .A1(_121_),
    .A2(_101_),
    .A3(_122_),
    .B1(_123_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__xor2_1 _218_ (
    .A(DUTY_CYCLE[0]),
    .B(_101_),
    .X(_042_)
  );
  sky130_fd_sc_hd__nor4_1 _219_ (
    .A(counter_debounce[3]),
    .B(counter_debounce[4]),
    .C(counter_debounce[11]),
    .D(counter_debounce[12]),
    .Y(_124_)
  );
  sky130_fd_sc_hd__nand4_1 _220_ (
    .A(_089_),
    .B(_070_),
    .C(_079_),
    .D(_124_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__nor2_1 _221_ (
    .A(_125_),
    .B(_061_),
    .Y(_001_[0])
  );
  sky130_fd_sc_hd__clkinv_1 _222_ (
    .A(counter_PWM[3]),
    .Y(_126_)
  );
  sky130_fd_sc_hd__clkinv_1 _223_ (
    .A(counter_PWM[2]),
    .Y(_127_)
  );
  sky130_fd_sc_hd__nor2_1 _224_ (
    .A(counter_PWM[0]),
    .B(counter_PWM[1]),
    .Y(_128_)
  );
  sky130_fd_sc_hd__a21oi_1 _225_ (
    .A1(_128_),
    .A2(_127_),
    .B1(_126_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__nor2_1 _226_ (
    .A(counter_PWM[0]),
    .B(_129_),
    .Y(_000_[0])
  );
  sky130_fd_sc_hd__nand2_1 _227_ (
    .A(counter_PWM[0]),
    .B(counter_PWM[1]),
    .Y(_130_)
  );
  sky130_fd_sc_hd__clkinv_1 _228_ (
    .A(_130_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nor3_1 _229_ (
    .A(counter_PWM[3]),
    .B(_128_),
    .C(_131_),
    .Y(_000_[1])
  );
  sky130_fd_sc_hd__a21oi_1 _230_ (
    .A1(_131_),
    .A2(counter_PWM[2]),
    .B1(counter_PWM[3]),
    .Y(_132_)
  );
  sky130_fd_sc_hd__o21a_1 _231_ (
    .A1(counter_PWM[2]),
    .A2(_131_),
    .B1(_132_),
    .X(_000_[2])
  );
  sky130_fd_sc_hd__nor2_1 _232_ (
    .A(_129_),
    .B(_132_),
    .Y(_000_[3])
  );
  sky130_fd_sc_hd__nand2_1 _233_ (
    .A(_103_),
    .B(counter_PWM[1]),
    .Y(_133_)
  );
  sky130_fd_sc_hd__o22ai_1 _234_ (
    .A1(counter_PWM[0]),
    .A2(_104_),
    .B1(_103_),
    .B2(counter_PWM[1]),
    .Y(_134_)
  );
  sky130_fd_sc_hd__a22oi_1 _235_ (
    .A1(DUTY_CYCLE[2]),
    .A2(_127_),
    .B1(_134_),
    .B2(_133_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__o22ai_1 _236_ (
    .A1(DUTY_CYCLE[3]),
    .A2(_126_),
    .B1(DUTY_CYCLE[2]),
    .B2(_127_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__o22ai_1 _237_ (
    .A1(_110_),
    .A2(counter_PWM[3]),
    .B1(_136_),
    .B2(_135_),
    .Y(PWM_OUT)
  );
  sky130_fd_sc_hd__clkinv_1 _238_ (
    .A(reset),
    .Y(_002_)
  );
  sky130_fd_sc_hd__clkinv_1 _239_ (
    .A(reset),
    .Y(_003_)
  );
  sky130_fd_sc_hd__clkinv_1 _240_ (
    .A(reset),
    .Y(_004_)
  );
  sky130_fd_sc_hd__clkinv_1 _241_ (
    .A(reset),
    .Y(_005_)
  );
  sky130_fd_sc_hd__clkinv_1 _242_ (
    .A(reset),
    .Y(_006_)
  );
  sky130_fd_sc_hd__clkinv_1 _243_ (
    .A(reset),
    .Y(_007_)
  );
  sky130_fd_sc_hd__clkinv_1 _244_ (
    .A(reset),
    .Y(_008_)
  );
  sky130_fd_sc_hd__clkinv_1 _245_ (
    .A(reset),
    .Y(_009_)
  );
  sky130_fd_sc_hd__clkinv_1 _246_ (
    .A(reset),
    .Y(_010_)
  );
  sky130_fd_sc_hd__clkinv_1 _247_ (
    .A(reset),
    .Y(_011_)
  );
  sky130_fd_sc_hd__clkinv_1 _248_ (
    .A(reset),
    .Y(_012_)
  );
  sky130_fd_sc_hd__clkinv_1 _249_ (
    .A(reset),
    .Y(_013_)
  );
  sky130_fd_sc_hd__clkinv_1 _250_ (
    .A(reset),
    .Y(_014_)
  );
  sky130_fd_sc_hd__clkinv_1 _251_ (
    .A(reset),
    .Y(_015_)
  );
  sky130_fd_sc_hd__clkinv_1 _252_ (
    .A(reset),
    .Y(_016_)
  );
  sky130_fd_sc_hd__clkinv_1 _253_ (
    .A(reset),
    .Y(_017_)
  );
  sky130_fd_sc_hd__clkinv_1 _254_ (
    .A(reset),
    .Y(_018_)
  );
  sky130_fd_sc_hd__clkinv_1 _255_ (
    .A(reset),
    .Y(_019_)
  );
  sky130_fd_sc_hd__clkinv_1 _256_ (
    .A(reset),
    .Y(_020_)
  );
  sky130_fd_sc_hd__clkinv_1 _257_ (
    .A(reset),
    .Y(_021_)
  );
  sky130_fd_sc_hd__clkinv_1 _258_ (
    .A(reset),
    .Y(_022_)
  );
  sky130_fd_sc_hd__clkinv_1 _259_ (
    .A(reset),
    .Y(_023_)
  );
  sky130_fd_sc_hd__clkinv_1 _260_ (
    .A(reset),
    .Y(_024_)
  );
  sky130_fd_sc_hd__clkinv_1 _261_ (
    .A(reset),
    .Y(_025_)
  );
  sky130_fd_sc_hd__clkinv_1 _262_ (
    .A(reset),
    .Y(_026_)
  );
  sky130_fd_sc_hd__clkinv_1 _263_ (
    .A(reset),
    .Y(_027_)
  );
  sky130_fd_sc_hd__clkinv_1 _264_ (
    .A(reset),
    .Y(_028_)
  );
  sky130_fd_sc_hd__clkinv_1 _265_ (
    .A(reset),
    .Y(_029_)
  );
  sky130_fd_sc_hd__clkinv_1 _266_ (
    .A(reset),
    .Y(_030_)
  );
  sky130_fd_sc_hd__clkinv_1 _267_ (
    .A(reset),
    .Y(_031_)
  );
  sky130_fd_sc_hd__clkinv_1 _268_ (
    .A(reset),
    .Y(_032_)
  );
  sky130_fd_sc_hd__clkinv_1 _269_ (
    .A(reset),
    .Y(_033_)
  );
  sky130_fd_sc_hd__clkinv_1 _270_ (
    .A(reset),
    .Y(_034_)
  );
  sky130_fd_sc_hd__clkinv_1 _271_ (
    .A(reset),
    .Y(_035_)
  );
  sky130_fd_sc_hd__clkinv_1 _272_ (
    .A(reset),
    .Y(_036_)
  );
  sky130_fd_sc_hd__clkinv_1 _273_ (
    .A(reset),
    .Y(_037_)
  );
  sky130_fd_sc_hd__clkinv_1 _274_ (
    .A(reset),
    .Y(_038_)
  );
  sky130_fd_sc_hd__clkinv_1 _275_ (
    .A(reset),
    .Y(_039_)
  );
  sky130_fd_sc_hd__clkinv_1 _276_ (
    .A(reset),
    .Y(_040_)
  );
  sky130_fd_sc_hd__clkinv_1 _277_ (
    .A(reset),
    .Y(_041_)
  );
  sky130_fd_sc_hd__dfstp_2 _278_ (
    .CLK(clk),
    .D(_042_),
    .Q(DUTY_CYCLE[0]),
    .SET_B(_002_)
  );
  sky130_fd_sc_hd__dfrtp_1 _279_ (
    .CLK(clk),
    .D(_043_),
    .Q(DUTY_CYCLE[1]),
    .RESET_B(_003_)
  );
  sky130_fd_sc_hd__dfstp_2 _280_ (
    .CLK(clk),
    .D(_044_),
    .Q(DUTY_CYCLE[2]),
    .SET_B(_004_)
  );
  sky130_fd_sc_hd__dfrtp_1 _281_ (
    .CLK(clk),
    .D(_045_),
    .Q(DUTY_CYCLE[3]),
    .RESET_B(_005_)
  );
  sky130_fd_sc_hd__dfrtp_1 _282_ (
    .CLK(clk),
    .D(_001_[0]),
    .Q(counter_debounce[0]),
    .RESET_B(_006_)
  );
  sky130_fd_sc_hd__dfrtp_1 _283_ (
    .CLK(clk),
    .D(1'h0),
    .Q(counter_debounce[1]),
    .RESET_B(_007_)
  );
  sky130_fd_sc_hd__dfrtp_1 _284_ (
    .CLK(clk),
    .D(1'h0),
    .Q(counter_debounce[2]),
    .RESET_B(_008_)
  );
  sky130_fd_sc_hd__dfrtp_1 _285_ (
    .CLK(clk),
    .D(1'h0),
    .Q(counter_debounce[3]),
    .RESET_B(_009_)
  );
  sky130_fd_sc_hd__dfrtp_1 _286_ (
    .CLK(clk),
    .D(1'h0),
    .Q(counter_debounce[4]),
    .RESET_B(_010_)
  );
  sky130_fd_sc_hd__dfrtp_1 _287_ (
    .CLK(clk),
    .D(1'h0),
    .Q(counter_debounce[5]),
    .RESET_B(_011_)
  );
  sky130_fd_sc_hd__dfrtp_1 _288_ (
    .CLK(clk),
    .D(1'h0),
    .Q(counter_debounce[6]),
    .RESET_B(_012_)
  );
  sky130_fd_sc_hd__dfrtp_1 _289_ (
    .CLK(clk),
    .D(1'h0),
    .Q(counter_debounce[7]),
    .RESET_B(_013_)
  );
  sky130_fd_sc_hd__dfrtp_1 _290_ (
    .CLK(clk),
    .D(1'h0),
    .Q(counter_debounce[8]),
    .RESET_B(_014_)
  );
  sky130_fd_sc_hd__dfrtp_1 _291_ (
    .CLK(clk),
    .D(1'h0),
    .Q(counter_debounce[9]),
    .RESET_B(_015_)
  );
  sky130_fd_sc_hd__dfrtp_1 _292_ (
    .CLK(clk),
    .D(1'h0),
    .Q(counter_debounce[10]),
    .RESET_B(_016_)
  );
  sky130_fd_sc_hd__dfrtp_1 _293_ (
    .CLK(clk),
    .D(1'h0),
    .Q(counter_debounce[11]),
    .RESET_B(_017_)
  );
  sky130_fd_sc_hd__dfrtp_1 _294_ (
    .CLK(clk),
    .D(1'h0),
    .Q(counter_debounce[12]),
    .RESET_B(_018_)
  );
  sky130_fd_sc_hd__dfrtp_1 _295_ (
    .CLK(clk),
    .D(1'h0),
    .Q(counter_debounce[13]),
    .RESET_B(_019_)
  );
  sky130_fd_sc_hd__dfrtp_1 _296_ (
    .CLK(clk),
    .D(1'h0),
    .Q(counter_debounce[14]),
    .RESET_B(_020_)
  );
  sky130_fd_sc_hd__dfrtp_1 _297_ (
    .CLK(clk),
    .D(1'h0),
    .Q(counter_debounce[15]),
    .RESET_B(_021_)
  );
  sky130_fd_sc_hd__dfrtp_1 _298_ (
    .CLK(clk),
    .D(1'h0),
    .Q(counter_debounce[16]),
    .RESET_B(_022_)
  );
  sky130_fd_sc_hd__dfrtp_1 _299_ (
    .CLK(clk),
    .D(1'h0),
    .Q(counter_debounce[17]),
    .RESET_B(_023_)
  );
  sky130_fd_sc_hd__dfrtp_1 _300_ (
    .CLK(clk),
    .D(1'h0),
    .Q(counter_debounce[18]),
    .RESET_B(_024_)
  );
  sky130_fd_sc_hd__dfrtp_1 _301_ (
    .CLK(clk),
    .D(1'h0),
    .Q(counter_debounce[19]),
    .RESET_B(_025_)
  );
  sky130_fd_sc_hd__dfrtp_1 _302_ (
    .CLK(clk),
    .D(1'h0),
    .Q(counter_debounce[20]),
    .RESET_B(_026_)
  );
  sky130_fd_sc_hd__dfrtp_1 _303_ (
    .CLK(clk),
    .D(1'h0),
    .Q(counter_debounce[21]),
    .RESET_B(_027_)
  );
  sky130_fd_sc_hd__dfrtp_1 _304_ (
    .CLK(clk),
    .D(1'h0),
    .Q(counter_debounce[22]),
    .RESET_B(_028_)
  );
  sky130_fd_sc_hd__dfrtp_1 _305_ (
    .CLK(clk),
    .D(1'h0),
    .Q(counter_debounce[23]),
    .RESET_B(_029_)
  );
  sky130_fd_sc_hd__dfrtp_1 _306_ (
    .CLK(clk),
    .D(1'h0),
    .Q(counter_debounce[24]),
    .RESET_B(_030_)
  );
  sky130_fd_sc_hd__dfrtp_1 _307_ (
    .CLK(clk),
    .D(1'h0),
    .Q(counter_debounce[25]),
    .RESET_B(_031_)
  );
  sky130_fd_sc_hd__dfrtp_1 _308_ (
    .CLK(clk),
    .D(1'h0),
    .Q(counter_debounce[26]),
    .RESET_B(_032_)
  );
  sky130_fd_sc_hd__dfrtp_1 _309_ (
    .CLK(clk),
    .D(1'h0),
    .Q(counter_debounce[27]),
    .RESET_B(_033_)
  );
  sky130_fd_sc_hd__dfrtp_1 _310_ (
    .CLK(clk),
    .D(_046_),
    .Q(tmp1),
    .RESET_B(_034_)
  );
  sky130_fd_sc_hd__dfrtp_1 _311_ (
    .CLK(clk),
    .D(_047_),
    .Q(tmp2),
    .RESET_B(_035_)
  );
  sky130_fd_sc_hd__dfrtp_1 _312_ (
    .CLK(clk),
    .D(_048_),
    .Q(tmp3),
    .RESET_B(_036_)
  );
  sky130_fd_sc_hd__dfrtp_1 _313_ (
    .CLK(clk),
    .D(_000_[0]),
    .Q(counter_PWM[0]),
    .RESET_B(_037_)
  );
  sky130_fd_sc_hd__dfrtp_1 _314_ (
    .CLK(clk),
    .D(_000_[1]),
    .Q(counter_PWM[1]),
    .RESET_B(_038_)
  );
  sky130_fd_sc_hd__dfrtp_1 _315_ (
    .CLK(clk),
    .D(_000_[2]),
    .Q(counter_PWM[2]),
    .RESET_B(_039_)
  );
  sky130_fd_sc_hd__dfrtp_1 _316_ (
    .CLK(clk),
    .D(_000_[3]),
    .Q(counter_PWM[3]),
    .RESET_B(_040_)
  );
  sky130_fd_sc_hd__dfrtp_1 _317_ (
    .CLK(clk),
    .D(_049_),
    .Q(tmp4),
    .RESET_B(_041_)
  );
  assign _001_[27:1] = 27'h0000000;
endmodule
